### ISSUE TITLE
Code block highlight didn't work

### ISSUE THREAD

**Issue by TyrantLucifer** [qdm12/stackedit-docker#11]
Hi @qdm12, thanks for your work!
I'm using almost daily stackedit with your docker image.
But I found a problem about the highlight of code block. It seems that do not work.  I try to build stackedit by myself, but appear the same problem. Could you help me to solve it?😋
![image](https://user-images.githubusercontent.com/51053924/106876094-551d7c00-6712-11eb-813a-1be9aff11bf0.png)

**Comment by qdm12** [comment]
Hello! I'll update the stackedit version over the weekend, maybe that will help. I'll ping you here once it's done.

**Comment by TyrantLucifer** [comment]
Thank you for your reply. I am waiting for you good message!

**Comment by qdm12** [comment]
Just had a quick look and it's actually still updated with Stackedit 5.14.5 which is their latest release. I'll try your example more in the coming week. Maybe that's an issue with the actual stackedit program: https://github.com/benweet/stackedit 🤔

**Comment by TyrantLucifer** [comment]
In stackedit.io, the problem is not appear, what a strange problem it is.😂 The version build by ourselves doesn't work normally. What do you think we raise an issue for actual stackedit?

**Comment by lorenx** [comment]
Hello.
I'm not actually using this project, I built my own Dockerfile (I cloned _StackEdit_ `v5.14.10` tag), but I run into the same issue.

It seems related to _Prismjs_ and you can also trigger it by going to `Menu / Settings`, since it'll try to highlight YAML code there:

![Menu / Settings](https://user-images.githubusercontent.com/890454/132129419-d6cdab53-d7f8-4234-a95a-018a1e4d7979.png)

There's one weird thing I noticed though...
If I build _StackEdit_ without using Docker, _Prismjs_ highlights things without any issue... but inside Docker the error occurs (and since it happens inside your container as well, it's an interesting coincidence).

I'll keep on debugging things here, let me know if you find any solution.
Thank you.

**Comment by qdm12** [comment]
Thanks @lorenx for your help. Well I spent an hour trying to build my own image without success, since stackedit is a dependency nightmare... I will eventually get to this, but ughh I am feeling like archiving this repository right now!

**Comment by lorenx** [comment]
Ok, I found it!
It's because docker runs with root privileges and npm complains about it.

Outside Docker, at some point during `npm install`, it says:
```
> stackedit@5.14.10 postinstall /srv/stackedit-fork
> gulp build-prism

[22:47:55] Using gulpfile /srv/stackedit-fork/gulpfile.js
[22:47:55] Starting 'build-prism'...
[22:47:56] Finished 'build-prism' after 118 ms
```

But when running inside Docker I suddenly noticed this:
```
npm WARN lifecycle stackedit@5.14.10~postinstall: cannot run in wd stackedit@5.14.10 gulp build-prism (wd=/srv/stackedit-fork)
```

And this breaks PrismJS somehow.

To fix it, I did `npm install --unsafe-perm`, as they say [here](https://stackoverflow.com/a/19132229).

---

About the dependencies, there are many that can be upgraded but yeah, it's a nightmare.
I kept everything as it is in `v5.14.10`, I only upgraded `katex: ^0.13.18` and it runs nicely.

Let me know if it works for you as well.

**Comment by qdm12** [comment]
> It's because docker runs with root privileges and npm complains about it.

@lorenx Do you mean at build time or runtime? 

- If this is build time, my build got magically fixed by using the last version v5.14.10. I still use `npm install` only and it works.
- If this is runtime, in my situation, it's a static binary (Go) and static assets only. Upgrading to v5.14.10 seems to have fixed the issue, pointing to a bug in stackedit?

@TyrantLucifer 1c88c9cfb57ea69c2f6c57071c37c1ed57d1e71c should had fixed it, you can try pulling the latest image; for me syntax highlighting (tried Java) works. Let me know if I misunderstood the problem.

**Comment by TyrantLucifer** [comment]
It works. Thank you for your good job.

**Comment by lorenx** [comment]
> Do you mean at build time or runtime?

@qdm12 Well, it depends when you run `npm install` (I don't use Go).
I'm doing it at build time to have my application fully versioned and ready to use.

Anyway, I'm not sure it changed that much from v5.14.5 to v5.14.10, but it's good it's working now.
